name: Deploy Node App

on:
  push:
    branches:
      - main

env:
  # This silences the Node 20 deprecation warnings
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and Push Backend
        # We tell Docker to look inside the /backend folder for the Dockerfile
        run: |
          docker build -t gatete/my-backend:latest ./backend
          docker push gatete/my-backend:latest

      - name: Build and Push Frontend
        # We tell Docker to look inside the /frontend folder for the Dockerfile
        run: |
          docker build -t gatete/my-frontend:latest ./frontend
          docker push gatete/my-frontend:latest
