name: Production Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend-web/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # No caching here, so it won't look for a root lock file

      - name: Install & Test Backend
        run: |
          cd backend
          npm install
          npm test

      - name: Install & Test Frontend
        # Added this so you are testing both parts of your monorepo
        run: |
          cd frontend-web
          npm install
          npm test
